############################################################################################################
#NAME:  SNAKEMAKE
#AUTHOR: Christophe Van den Eynde
#RUNNING: Hybrid assembly short read preparation
#USAGE: $snakemake
############################################################################################################

#SNAKEMAKE RUN PREPARATION==================================================================================
# GET INFO FROM HOST----------------------------------------------------------------------------------------
env = open("/home/Pipeline/environment.txt","r")
for line in env.readlines():
    if "Results_m=" in line:
        Results_m = line.replace("Results_m=",'').replace('\n','')
        Results_m = Results_m
    elif "Scripts_m" in line:
        Scripts_m = line.replace("Scripts_m=",'').replace('\n','')
    elif "Threads=" in line:
        Threads = line.replace("Threads=",'').replace('\n','')
env.close()
#-----------------------------------------------------------------------------------------------------------

#GET SAMPLE IDS---------------------------------------------------------------------------------------------
ids = []
samples = open("/home/Pipeline/Hybrid/sampleList.txt","r")
for line in samples.readlines():
    ids.append(line.replace('\n',''))
samples.close()
#-----------------------------------------------------------------------------------------------------------
#===========================================================================================================

#SNAKEMAKE RUN==============================================================================================
#-----------------------------------------------------------------------------------------------------------
# Master rule, controls all other rule executions

rule all:                                                                       
    input:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_MultiQC/multiqc_report.html",id=ids),                            
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/03_QC-Trimmomatic_Paired/QC_MultiQC/multiqc_report.html",id=ids),                                                                    
    message:
        "Analysis done, results can be found in {Results_m}"

#-----------------------------------------------------------------------------------------------------------
# Pipeline step1: copy/move files from raw data folder to 'Sample_id/00_Rawdata/' in the analysis-results folder
# executed in get_environment.py

#-----------------------------------------------------------------------------------------------------------
# Pipeline step2: running fastqc on the raw-data in the current-analysis folder

rule fastqc_raw:
    input:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/00_Rawdata/{id}_L001_R1_001.fastq.gz",id=ids),  #the rawdata (output copy_rawdata rule)
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/00_Rawdata/{id}_L001_R2_001.fastq.gz",id=ids)   #the rawdata (output copy_rawdata rule)
    output:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_FastQC/{id}_L001_R1_001_fastqc.html",id=ids),
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_FastQC/{id}_L001_R2_001_fastqc.html",id=ids)
    message:
        "Analyzing raw-data with FastQC using Docker-container fastqc:v2.2_stable"
    shell:
        'docker run -it --rm \
        --name fastqc_raw \
        -v "{Scripts_m}:/home/Scripts/" \
        -v "{Results_m}:/home/Pipeline/" \
        christophevde/fastqc:v2.2_stable \
        /bin/bash -c "dos2unix /home/Scripts/Hybrid/Short_read/QC01_FastQC_Raw.sh \
        && /home/Scripts/Hybrid/Short_read/QC01_FastQC_Raw.sh {Threads}"'

#-----------------------------------------------------------------------------------------------------------
# Pipeline step3: running multiqc on the raw-data in the current-analysis folder

rule multiqc_raw:
    input:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_FastQC/{id}_L001_R1_001_fastqc.html",id=ids),    #output fastqc rawdata
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_FastQC/{id}_L001_R2_001_fastqc.html",id=ids)     #output fastqc rawdata
    output:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_MultiQC/multiqc_report.html",id=ids)             #Results MultiQC for each sample separately
    message:
        "Analyzing raw-data with MultiQC using Docker-container multiqc:v2.2_stable"
    shell:
        'docker run -it --rm \
        --name multiqc_raw \
        -v "{Scripts_m}:/home/Scripts/" \
        -v "{Results_m}:/home/Pipeline/" \
        christophevde/multiqc:v2.2_stable \
        /bin/bash -c "dos2unix /home/Scripts/Hybrid/Short_read/QC01_MultiQC_Raw.sh \
        && /home/Scripts/Hybrid/Short_read/QC01_MultiQC_Raw.sh"'

#-----------------------------------------------------------------------------------------------------------
# Pipeline step4: Trimming

rule Trimming:
    input:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/00_Rawdata/{id}_L001_R1_001.fastq.gz",id=ids),          #the rawdata (output copy_rawdata rule)
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/00_Rawdata/{id}_L001_R2_001.fastq.gz",id=ids),          #the rawdata (output copy_rawdata rule)
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/01_QC-Rawdata/QC_MultiQC/multiqc_report.html",id=ids)   #output multiqc raw (required so that the tasks don't run simultaniously and their outpur gets mixed in the terminal)
    output:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/02_Trimmomatic/{id}_L001_R1_001_P.fastq.gz",id=ids),
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/02_Trimmomatic/{id}_L001_R2_001_U.fastq.gz",id=ids)
    message:
        "Trimming raw-data with Trimmomatic v0.39 using Docker-container trimmomatic:v2.2_stable"
    shell:
        'docker run -it --rm \
        --name trimmomatic \
        -v "{Scripts_m}:/home/Scripts/" \
        -v "{Results_m}:/home/Pipeline/" \
        christophevde/trimmomatic:v2.2_stable \
        /bin/bash -c "dos2unix /home/Scripts/Hybrid/Short_read/02_runTrimmomatic.sh \
        && /home/Scripts/Hybrid/Short_read/02_runTrimmomatic.sh {Threads}"'

#-----------------------------------------------------------------------------------------------------------
# Pipeline step5: FastQC trimmed data (paired reads only)

rule fastqc_trimmed:
    input:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/02_Trimmomatic/{id}_L001_R1_001_P.fastq.gz",id=ids), #output trimmomatic
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/02_Trimmomatic/{id}_L001_R2_001_U.fastq.gz",id=ids)  #output trimmomatic
    output:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/03_QC-Trimmomatic_Paired/QC_FastQC/{id}_L001_R1_001_P_fastqc.html",id=ids)
    message:
        "Analyzing trimmed-data with FastQC using Docker-container fastqc:v2.2_stable"
    shell:
        'docker run -it --rm \
        --name fastqc_trim \
        -v "{Scripts_m}:/home/Scripts/" \
        -v "{Results_m}:/home/Pipeline/" \
        christophevde/fastqc:v2.2_stable \
        /bin/bash -c "dos2unix /home/Scripts/Short_read/Hybrid/QC01_FastQC_Trim.sh \
        && /home/Scripts/Short_read/Hybrid/QC01_FastQC_Trim.sh {Threads}"'

#-----------------------------------------------------------------------------------------------------------
# Pipeline step6: MultiQC trimmed data (paired reads only) 

rule multiqc_trimmed:
    input:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/03_QC-Trimmomatic_Paired/QC_FastQC/{id}_L001_R1_001_P_fastqc.html",id=ids)      #output fastqc trimmed data
    output:
        expand("/home/Pipeline/Hybrid/{id}/Short_reads/03_QC-Trimmomatic_Paired/QC_MultiQC/multiqc_report.html",id=ids)
    message:
        "Analyzing trimmed-data with MultiQC using Docker-container multiqc:v2.2_stable"
    shell:
        'docker run -it --rm \
        --name multiqc_trim \
        -v "{Scripts_m}:/home/Scripts/" \
        -v "{Results_m}:/home/Pipeline/" \
        christophevde/multiqc:v2.2_stable \
        /bin/bash -c "dos2unix /home/Scripts/Short_read/QC02_MultiQC_Trim.sh \
        && /home/Scripts/Short_read/QC02_MultiQC_Trim.sh"'
#===========================================================================================================